name: Build and Push Jitsi Meet

on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build Debian Package and Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    
    - name: Build Debian package
      run: |
        sudo apt-get update
        sudo apt-get install -y debhelper devscripts build-essential
        npm install
        make
        dpkg-buildpackage -b -rfakeroot -us -uc
        mkdir -p docker-build
        mv ../*.deb docker-build/
    
    - name: Copy rootfs
      run: cp -r rootfs docker-build/
    
    - name: Create Dockerfile
      run: |
        cat << EOF > docker-build/Dockerfile
        ARG JITSI_REPO=jitsi
        ARG BASE_TAG=stable
        FROM \${JITSI_REPO}/base:\${BASE_TAG}
        
        LABEL org.opencontainers.image.title="Athenia AI Meet"
        LABEL org.opencontainers.image.description="WebRTC compatible scalable video conferences."
        LABEL org.opencontainers.image.url="https://atheniaai.com/"
        LABEL org.opencontainers.image.source="https://github.com/atheniaai/"
        LABEL org.opencontainers.image.documentation="https://atheniaai.github.io/"
        
        ADD https://raw.githubusercontent.com/acmesh-official/acme.sh/3.0.7/acme.sh /opt
        COPY rootfs/ /
        COPY *.deb /tmp/
        
        # Install dependencies
        RUN export DEBIAN_FRONTEND=noninteractive && \
            apt-get update && \
            apt-get install -y dnsutils cron nginx-extras socat curl jq && \
            dpkg -i /tmp/*.deb && \
            apt-get install -f -y && \
            mv /usr/share/jitsi-meet/interface_config.js /defaults && \
            rm -f /etc/nginx/conf.d/default.conf && \
            rm -f /tmp/*.deb && \
            apt-get clean && \
            rm -rf /var/lib/apt/lists/*
        
        EXPOSE 80 443
        VOLUME ["/config", "/usr/share/jitsi-meet/transcripts"]
        EOF
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: docker-build
        push: true
        tags: atheniaai/meet:latest
